// 🦐 高级虾虾卡牌数据
// 生成时间: 2026-03-12 12:11:25
// 卡牌数量: 50
// 战斗力公式: 125 种

const advancedShrimpCards = [
  {
    "id": "SHRIMP_121125_3666",
    "name": "沉重虾后",
    "cost": 1,
    "attack": 18,
    "health": 4,
    "wish": "文艺",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "独特",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 22.79,
    "formula_key": "文艺_勇敢_独特",
    "special_ability": "艺术灵感",
    "description": "一只勇敢的虾虾，怀有文艺的愿望，审美偏向独特。 战斗力适中，战斗值约为23点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.899,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.8,
      "bias_difference": 0.1
    },
    "attack_ratio": 0.8,
    "health_ratio": 0.2
  },
  {
    "id": "SHRIMP_121125_2298",
    "name": "内向虾舞",
    "cost": 1,
    "attack": 7,
    "health": 9,
    "wish": "战斗",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "酷炫",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 19.33,
    "formula_key": "战斗_狂野_酷炫",
    "special_ability": "战斗狂热",
    "description": "这只虾虾以狂野著称，心中燃烧着战斗的火焰，喜欢酷炫的风格。 战斗力适中，战斗值约为19点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.593,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.336,
      "bias_difference": 0.164
    },
    "attack_ratio": 0.336,
    "health_ratio": 0.664
  },
  {
    "id": "SHRIMP_121125_3859",
    "name": "轻盈虾影",
    "cost": 1,
    "attack": 4,
    "health": 17,
    "wish": "霸气",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 18.49,
    "formula_key": "霸气_狂野_华丽",
    "special_ability": "霸气领域",
    "description": "一只狂野的虾虾，怀有霸气的愿望，审美偏向华丽。 战斗力适中，战斗值约为18点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.541,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "偏离性格偏好",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.177,
      "bias_difference": 0.323
    },
    "attack_ratio": 0.177,
    "health_ratio": 0.823
  },
  {
    "id": "SHRIMP_121125_8350",
    "name": "调皮虾术",
    "cost": 1,
    "attack": 7,
    "health": 10,
    "wish": "战斗",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "独特",
    "rarity": "传说",
    "rarity_color": "#FF6B6B",
    "combat_value": 17.6,
    "formula_key": "战斗_沉稳_独特",
    "special_ability": "战斗狂热",
    "description": "拥有沉稳性格的虾虾，致力于战斗的事业，崇尚独特的美学。 战斗力适中，战斗值约为18点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.98,
      "range_min": 0,
      "range_max": 12,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.312,
      "bias_difference": 0.088
    },
    "attack_ratio": 0.312,
    "health_ratio": 0.688
  },
  {
    "id": "SHRIMP_121125_8906",
    "name": "灵动虾灵",
    "cost": 1,
    "attack": 3,
    "health": 12,
    "wish": "治愈",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "梦幻",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 15.58,
    "formula_key": "治愈_智慧_梦幻",
    "special_ability": "治愈之光",
    "description": "这只虾虾以智慧著称，心中燃烧着治愈的火焰，喜欢梦幻的风格。 战斗力适中，战斗值约为16点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.298,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.267,
      "bias_difference": 0.033
    },
    "attack_ratio": 0.267,
    "health_ratio": 0.733
  },
  {
    "id": "SHRIMP_121125_4198",
    "name": "明亮虾德",
    "cost": 1,
    "attack": 9,
    "health": 7,
    "wish": "治愈",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 14.45,
    "formula_key": "治愈_狡猾_华丽",
    "special_ability": "治愈之光",
    "description": "拥有狡猾性格的虾虾，致力于治愈的事业，崇尚华丽的美学。 战斗力适中，战斗值约为14点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.204,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.666,
      "bias_difference": 0.066
    },
    "attack_ratio": 0.666,
    "health_ratio": 0.334
  },
  {
    "id": "SHRIMP_121125_4852",
    "name": "勇敢虾宝",
    "cost": 1,
    "attack": 5,
    "health": 10,
    "wish": "文艺",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 14.41,
    "formula_key": "文艺_沉稳_华丽",
    "special_ability": "艺术灵感",
    "description": "一只沉稳的虾虾，怀有文艺的愿望，审美偏向华丽。 战斗力适中，战斗值约为14点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.201,
      "range_min": 12,
      "range_max": 24,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.37,
      "bias_difference": 0.03
    },
    "attack_ratio": 0.37,
    "health_ratio": 0.63
  },
  {
    "id": "SHRIMP_121125_3811",
    "name": "厚重虾宝",
    "cost": 2,
    "attack": 6,
    "health": 27,
    "wish": "治愈",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "梦幻",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 38.68,
    "formula_key": "治愈_智慧_梦幻",
    "special_ability": "治愈之光",
    "description": "拥有智慧性格的虾虾，致力于治愈的事业，崇尚梦幻的美学。 战斗力适中，战斗值约为39点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.979,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.267,
      "bias_difference": 0.033
    },
    "attack_ratio": 0.267,
    "health_ratio": 0.733
  },
  {
    "id": "SHRIMP_121125_4028",
    "name": "文艺虾舞",
    "cost": 2,
    "attack": 15,
    "health": 30,
    "wish": "文艺",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 31.33,
    "formula_key": "文艺_狂野_独特",
    "special_ability": "艺术灵感",
    "description": "一只狂野的虾虾，怀有文艺的愿望，审美偏向独特。 战斗力适中，战斗值约为31点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.405,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.319,
      "bias_difference": 0.181
    },
    "attack_ratio": 0.319,
    "health_ratio": 0.681
  },
  {
    "id": "SHRIMP_121125_1908",
    "name": "开朗虾神",
    "cost": 2,
    "attack": 12,
    "health": 17,
    "wish": "战斗",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "华丽",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 30.18,
    "formula_key": "战斗_沉稳_华丽",
    "special_ability": "战斗狂热",
    "description": "一只战斗的虾虾，性格沉稳，审美华丽，在战场上稳扎稳打。 战斗力适中，战斗值约为30点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.314,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.336,
      "bias_difference": 0.064
    },
    "attack_ratio": 0.336,
    "health_ratio": 0.664
  },
  {
    "id": "SHRIMP_121125_5048",
    "name": "沉重虾梦",
    "cost": 2,
    "attack": 9,
    "health": 17,
    "wish": "治愈",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 29.57,
    "formula_key": "治愈_沉稳_华丽",
    "special_ability": "治愈之光",
    "description": "拥有沉稳性格的虾虾，致力于治愈的事业，崇尚华丽的美学。 战斗力适中，战斗值约为30点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.371,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.449,
      "bias_difference": 0.049
    },
    "attack_ratio": 0.449,
    "health_ratio": 0.551
  },
  {
    "id": "SHRIMP_121125_6559",
    "name": "狂野虾战",
    "cost": 2,
    "attack": 16,
    "health": 10,
    "wish": "神秘",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "梦幻",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 29.01,
    "formula_key": "神秘_勇敢_梦幻",
    "special_ability": "神秘护盾",
    "description": "这只虾虾以勇敢著称，心中燃烧着神秘的火焰，喜欢梦幻的风格。 战斗力适中，战斗值约为29点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.334,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.645,
      "bias_difference": 0.055
    },
    "attack_ratio": 0.645,
    "health_ratio": 0.355
  },
  {
    "id": "SHRIMP_121125_7332",
    "name": "华丽虾诗",
    "cost": 2,
    "attack": 4,
    "health": 21,
    "wish": "文艺",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 28.24,
    "formula_key": "文艺_智慧_华丽",
    "special_ability": "艺术灵感",
    "description": "这只虾虾以智慧著称，心中燃烧着文艺的火焰，喜欢华丽的风格。 战斗力适中，战斗值约为28点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.283,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.179,
      "bias_difference": 0.121
    },
    "attack_ratio": 0.179,
    "health_ratio": 0.821
  },
  {
    "id": "SHRIMP_121125_8689",
    "name": "厚重虾后",
    "cost": 2,
    "attack": 5,
    "health": 18,
    "wish": "治愈",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "清新",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 24.28,
    "formula_key": "治愈_智慧_清新",
    "special_ability": "治愈之光",
    "description": "一只智慧的虾虾，怀有治愈的愿望，审美偏向清新。 战斗力适中，战斗值约为24点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.055,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.357,
      "bias_difference": 0.057
    },
    "attack_ratio": 0.357,
    "health_ratio": 0.643
  },
  {
    "id": "SHRIMP_121125_6218",
    "name": "机智虾仔",
    "cost": 3,
    "attack": 11,
    "health": 58,
    "wish": "霸气",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "独特",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 54.47,
    "formula_key": "霸气_狂野_独特",
    "special_ability": "霸气领域",
    "description": "这只虾虾以狂野著称，心中燃烧着霸气的火焰，喜欢独特的风格。 战斗力均衡，战斗值约为54点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.859,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "偏离性格偏好",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.135,
      "bias_difference": 0.365
    },
    "attack_ratio": 0.135,
    "health_ratio": 0.865
  },
  {
    "id": "SHRIMP_121125_5982",
    "name": "清新虾影",
    "cost": 3,
    "attack": 15,
    "health": 30,
    "wish": "霸气",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "清新",
    "rarity": "传说",
    "rarity_color": "#FF6B6B",
    "combat_value": 51.84,
    "formula_key": "霸气_沉稳_清新",
    "special_ability": "霸气领域",
    "description": "一只沉稳的虾虾，怀有霸气的愿望，审美偏向清新。 战斗力均衡，战斗值约为52点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.476,
      "range_min": 24,
      "range_max": 39,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.372,
      "bias_difference": 0.028
    },
    "attack_ratio": 0.372,
    "health_ratio": 0.628
  },
  {
    "id": "SHRIMP_121125_1229",
    "name": "沉稳虾影",
    "cost": 3,
    "attack": 47,
    "health": 10,
    "wish": "治愈",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 50.75,
    "formula_key": "治愈_勇敢_酷炫",
    "special_ability": "治愈之光",
    "description": "一只治愈的虾虾，性格勇敢，审美酷炫，在战场上勇往直前。 战斗力均衡，战斗值约为51点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.653,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.868,
      "bias_difference": 0.168
    },
    "attack_ratio": 0.868,
    "health_ratio": 0.132
  },
  {
    "id": "SHRIMP_121125_9921",
    "name": "明亮虾舞",
    "cost": 3,
    "attack": 19,
    "health": 25,
    "wish": "神秘",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "独特",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 47.82,
    "formula_key": "神秘_沉稳_独特",
    "special_ability": "神秘护盾",
    "description": "沉稳的虾虾，追寻着神秘的梦想，展现出独特的魅力。 战斗力适中，战斗值约为48点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.49,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.406,
      "bias_difference": 0.006
    },
    "attack_ratio": 0.406,
    "health_ratio": 0.594
  },
  {
    "id": "SHRIMP_121125_7245",
    "name": "华丽虾后",
    "cost": 3,
    "attack": 16,
    "health": 22,
    "wish": "神秘",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "华丽",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 40.62,
    "formula_key": "神秘_沉稳_华丽",
    "special_ability": "神秘护盾",
    "description": "这只虾虾以沉稳著称，心中燃烧着神秘的火焰，喜欢华丽的风格。 战斗力适中，战斗值约为41点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.159,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.459,
      "bias_difference": 0.059
    },
    "attack_ratio": 0.459,
    "health_ratio": 0.541
  },
  {
    "id": "SHRIMP_121125_9004",
    "name": "勇敢虾舞",
    "cost": 3,
    "attack": 12,
    "health": 26,
    "wish": "神秘",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 40.6,
    "formula_key": "神秘_智慧_酷炫",
    "special_ability": "神秘护盾",
    "description": "这只虾虾以智慧著称，心中燃烧着神秘的火焰，喜欢酷炫的风格。 战斗力适中，战斗值约为41点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.089,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.313,
      "bias_difference": 0.013
    },
    "attack_ratio": 0.313,
    "health_ratio": 0.687
  },
  {
    "id": "SHRIMP_121125_3429",
    "name": "轻盈虾将",
    "cost": 4,
    "attack": 34,
    "health": 46,
    "wish": "文艺",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "独特",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 75.7,
    "formula_key": "文艺_沉稳_独特",
    "special_ability": "艺术灵感",
    "description": "拥有沉稳性格的虾虾，致力于文艺的事业，崇尚独特的美学。 战斗力均衡，战斗值约为76点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.779,
      "range_min": 57,
      "range_max": 81,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.399,
      "bias_difference": 0.001
    },
    "attack_ratio": 0.399,
    "health_ratio": 0.601
  },
  {
    "id": "SHRIMP_121125_6048",
    "name": "沉稳虾巫",
    "cost": 4,
    "attack": 16,
    "health": 48,
    "wish": "治愈",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 68.44,
    "formula_key": "治愈_狂野_酷炫",
    "special_ability": "治愈之光",
    "description": "狂野的虾虾，追寻着治愈的梦想，展现出酷炫的魅力。 战斗力均衡，战斗值约为68点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.477,
      "range_min": 57,
      "range_max": 81,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.307,
      "bias_difference": 0.193
    },
    "attack_ratio": 0.307,
    "health_ratio": 0.693
  },
  {
    "id": "SHRIMP_121125_9389",
    "name": "活泼虾将",
    "cost": 4,
    "attack": 17,
    "health": 35,
    "wish": "神秘",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "清新",
    "rarity": "超级稀有",
    "rarity_color": "#FFD166",
    "combat_value": 57.0,
    "formula_key": "神秘_沉稳_清新",
    "special_ability": "神秘护盾",
    "description": "一只沉稳的虾虾，怀有神秘的愿望，审美偏向清新。 战斗力均衡，战斗值约为57点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.062,
      "range_min": 39,
      "range_max": 57,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.405,
      "bias_difference": 0.005
    },
    "attack_ratio": 0.405,
    "health_ratio": 0.595
  },
  {
    "id": "SHRIMP_121125_4064",
    "name": "智慧虾将",
    "cost": 5,
    "attack": 100,
    "health": 20,
    "wish": "治愈",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 107.74,
    "formula_key": "治愈_勇敢_华丽",
    "special_ability": "治愈之光",
    "description": "拥有勇敢性格的虾虾，致力于治愈的事业，崇尚华丽的美学。 战斗力不俗，战斗值约为108点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.955,
      "range_min": 81,
      "range_max": 109,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.881,
      "bias_difference": 0.181
    },
    "attack_ratio": 0.881,
    "health_ratio": 0.119
  },
  {
    "id": "SHRIMP_121125_1541",
    "name": "沉重虾骑",
    "cost": 5,
    "attack": 59,
    "health": 77,
    "wish": "治愈",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "清新",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 106.99,
    "formula_key": "治愈_狡猾_清新",
    "special_ability": "治愈之光",
    "description": "一只狡猾的虾虾，怀有治愈的愿望，审美偏向清新。 战斗力不俗，战斗值约为107点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.928,
      "range_min": 81,
      "range_max": 109,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.583,
      "bias_difference": 0.017
    },
    "attack_ratio": 0.583,
    "health_ratio": 0.417
  },
  {
    "id": "SHRIMP_121125_5661",
    "name": "梦幻虾剑",
    "cost": 5,
    "attack": 19,
    "health": 59,
    "wish": "治愈",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 98.67,
    "formula_key": "治愈_狂野_酷炫",
    "special_ability": "治愈之光",
    "description": "这只虾虾以狂野著称，心中燃烧着治愈的火焰，喜欢酷炫的风格。 战斗力均衡，战斗值约为99点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.631,
      "range_min": 81,
      "range_max": 109,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.307,
      "bias_difference": 0.193
    },
    "attack_ratio": 0.307,
    "health_ratio": 0.693
  },
  {
    "id": "SHRIMP_121125_8829",
    "name": "华丽虾宝",
    "cost": 5,
    "attack": 82,
    "health": 23,
    "wish": "文艺",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "酷炫",
    "rarity": "超级稀有",
    "rarity_color": "#FFD166",
    "combat_value": 96.96,
    "formula_key": "文艺_勇敢_酷炫",
    "special_ability": "艺术灵感",
    "description": "这只虾虾以勇敢著称，心中燃烧着文艺的火焰，喜欢酷炫的风格。 战斗力均衡，战斗值约为97点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.728,
      "range_min": 57,
      "range_max": 81,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.776,
      "bias_difference": 0.076
    },
    "attack_ratio": 0.776,
    "health_ratio": 0.224
  },
  {
    "id": "SHRIMP_121125_2658",
    "name": "文艺虾法",
    "cost": 5,
    "attack": 8,
    "health": 61,
    "wish": "文艺",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 86.69,
    "formula_key": "文艺_狂野_华丽",
    "special_ability": "艺术灵感",
    "description": "拥有狂野性格的虾虾，致力于文艺的事业，崇尚华丽的美学。 战斗力均衡，战斗值约为87点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.203,
      "range_min": 81,
      "range_max": 109,
      "bias_rating": "偏离性格偏好",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.126,
      "bias_difference": 0.374
    },
    "attack_ratio": 0.126,
    "health_ratio": 0.874
  },
  {
    "id": "SHRIMP_121125_3073",
    "name": "外向虾剑",
    "cost": 5,
    "attack": 20,
    "health": 67,
    "wish": "霸气",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 85.83,
    "formula_key": "霸气_智慧_独特",
    "special_ability": "霸气领域",
    "description": "智慧的虾虾，追寻着霸气的梦想，展现出独特的魅力。 战斗力均衡，战斗值约为86点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.292,
      "range_min": 81,
      "range_max": 109,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.202,
      "bias_difference": 0.098
    },
    "attack_ratio": 0.202,
    "health_ratio": 0.798
  },
  {
    "id": "SHRIMP_121125_4779",
    "name": "灵动虾后",
    "cost": 6,
    "attack": 74,
    "health": 36,
    "wish": "战斗",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 125.6,
    "formula_key": "战斗_狡猾_华丽",
    "special_ability": "战斗狂热",
    "description": "一只狡猾的虾虾，怀有战斗的愿望，审美偏向华丽。 战斗力不俗，战斗值约为126点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.503,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.604,
      "bias_difference": 0.004
    },
    "attack_ratio": 0.604,
    "health_ratio": 0.396
  },
  {
    "id": "SHRIMP_121125_8726",
    "name": "治愈虾魂",
    "cost": 6,
    "attack": 136,
    "health": 9,
    "wish": "神秘",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 125.41,
    "formula_key": "神秘_狂野_独特",
    "special_ability": "神秘护盾",
    "description": "拥有狂野性格的虾虾，致力于神秘的事业，崇尚独特的美学。 战斗力不俗，战斗值约为125点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.216,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "偏离性格偏好",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.926,
      "bias_difference": 0.426
    },
    "attack_ratio": 0.926,
    "health_ratio": 0.074
  },
  {
    "id": "SHRIMP_121125_7873",
    "name": "机智虾剑",
    "cost": 6,
    "attack": 86,
    "health": 62,
    "wish": "神秘",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "清新",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 124.22,
    "formula_key": "神秘_狡猾_清新",
    "special_ability": "神秘护盾",
    "description": "拥有狡猾性格的虾虾，致力于神秘的事业，崇尚清新的美学。 战斗力不俗，战斗值约为124点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.461,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.654,
      "bias_difference": 0.054
    },
    "attack_ratio": 0.654,
    "health_ratio": 0.346
  },
  {
    "id": "SHRIMP_121125_8122",
    "name": "活泼虾德",
    "cost": 6,
    "attack": 62,
    "health": 38,
    "wish": "霸气",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 110.0,
    "formula_key": "霸气_狡猾_酷炫",
    "special_ability": "霸气领域",
    "description": "狡猾的虾虾，追寻着霸气的梦想，展现出酷炫的魅力。 战斗力不俗，战斗值约为110点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.03,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.597,
      "bias_difference": 0.003
    },
    "attack_ratio": 0.597,
    "health_ratio": 0.403
  },
  {
    "id": "SHRIMP_121125_5976",
    "name": "智慧虾骑",
    "cost": 7,
    "attack": 94,
    "health": 96,
    "wish": "文艺",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "清新",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 177.59,
    "formula_key": "文艺_狡猾_清新",
    "special_ability": "艺术灵感",
    "description": "狡猾的虾虾，追寻着文艺的梦想，展现出清新的魅力。 战斗力不俗，战斗值约为178点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.989,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.571,
      "bias_difference": 0.029
    },
    "attack_ratio": 0.571,
    "health_ratio": 0.429
  },
  {
    "id": "SHRIMP_121125_2476",
    "name": "厚重虾侠",
    "cost": 7,
    "attack": 100,
    "health": 70,
    "wish": "神秘",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "独特",
    "rarity": "超级稀有",
    "rarity_color": "#FFD166",
    "combat_value": 174.72,
    "formula_key": "神秘_狡猾_独特",
    "special_ability": "神秘护盾",
    "description": "这只虾虾以狡猾著称，心中燃烧着神秘的火焰，喜欢独特的风格。 战斗力不俗，战斗值约为175点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.438,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.564,
      "bias_difference": 0.036
    },
    "attack_ratio": 0.564,
    "health_ratio": 0.436
  },
  {
    "id": "SHRIMP_121125_3701",
    "name": "温柔虾剑",
    "cost": 7,
    "attack": 116,
    "health": 16,
    "wish": "霸气",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "华丽",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 168.14,
    "formula_key": "霸气_勇敢_华丽",
    "special_ability": "霸气领域",
    "description": "一只霸气的虾虾，性格勇敢，审美华丽，在战场上勇往直前。 战斗力不俗，战斗值约为168点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.111,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.878,
      "bias_difference": 0.178
    },
    "attack_ratio": 0.878,
    "health_ratio": 0.122
  },
  {
    "id": "SHRIMP_121125_9072",
    "name": "开朗虾诗",
    "cost": 7,
    "attack": 34,
    "health": 112,
    "wish": "霸气",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 167.91,
    "formula_key": "霸气_智慧_独特",
    "special_ability": "霸气领域",
    "description": "拥有智慧性格的虾虾，致力于霸气的事业，崇尚独特的美学。 战斗力不俗，战斗值约为168点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.956,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.202,
      "bias_difference": 0.098
    },
    "attack_ratio": 0.202,
    "health_ratio": 0.798
  },
  {
    "id": "SHRIMP_121125_4030",
    "name": "霸气虾宝",
    "cost": 7,
    "attack": 49,
    "health": 113,
    "wish": "治愈",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "梦幻",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 159.01,
    "formula_key": "治愈_沉稳_梦幻",
    "special_ability": "治愈之光",
    "description": "一只治愈的虾虾，性格沉稳，审美梦幻，在战场上稳扎稳打。 战斗力不俗，战斗值约为159点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.472,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.42,
      "bias_difference": 0.02
    },
    "attack_ratio": 0.42,
    "health_ratio": 0.58
  },
  {
    "id": "SHRIMP_121125_3582",
    "name": "厚重虾神",
    "cost": 7,
    "attack": 85,
    "health": 71,
    "wish": "治愈",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 145.38,
    "formula_key": "治愈_狡猾_酷炫",
    "special_ability": "治愈之光",
    "description": "拥有狡猾性格的虾虾，致力于治愈的事业，崇尚酷炫的美学。 战斗力不俗，战斗值约为145点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.094,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.618,
      "bias_difference": 0.018
    },
    "attack_ratio": 0.618,
    "health_ratio": 0.382
  },
  {
    "id": "SHRIMP_121125_4726",
    "name": "勇敢虾画",
    "cost": 7,
    "attack": 90,
    "health": 59,
    "wish": "神秘",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "清新",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 145.09,
    "formula_key": "神秘_勇敢_清新",
    "special_ability": "神秘护盾",
    "description": "这只虾虾以勇敢著称，心中燃烧着神秘的火焰，喜欢清新的风格。 战斗力不俗，战斗值约为145点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.239,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.67,
      "bias_difference": 0.03
    },
    "attack_ratio": 0.67,
    "health_ratio": 0.33
  },
  {
    "id": "SHRIMP_121125_5662",
    "name": "狡猾虾魂",
    "cost": 7,
    "attack": 22,
    "health": 103,
    "wish": "霸气",
    "personality": "狂野",
    "personality_icon": "🐺",
    "personality_color": "#F56565",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 142.46,
    "formula_key": "霸气_狂野_华丽",
    "special_ability": "霸气领域",
    "description": "拥有狂野性格的虾虾，致力于霸气的事业，崇尚华丽的美学。 战斗力不俗，战斗值约为142点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.013,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "偏离性格偏好",
      "expected_attack_bias": 0.5,
      "actual_attack_ratio": 0.177,
      "bias_difference": 0.323
    },
    "attack_ratio": 0.177,
    "health_ratio": 0.823
  },
  {
    "id": "SHRIMP_121125_9414",
    "name": "狂野虾术",
    "cost": 8,
    "attack": 42,
    "health": 136,
    "wish": "霸气",
    "personality": "智慧",
    "personality_icon": "📚",
    "personality_color": "#4ECDC4",
    "aesthetic": "独特",
    "rarity": "传说",
    "rarity_color": "#FF6B6B",
    "combat_value": 207.17,
    "formula_key": "霸气_智慧_独特",
    "special_ability": "霸气领域",
    "description": "一只智慧的虾虾，怀有霸气的愿望，审美偏向独特。 拥有惊人的战斗力，战斗值约为207点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.31,
      "range_min": 109,
      "range_max": 142,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.3,
      "actual_attack_ratio": 0.202,
      "bias_difference": 0.098
    },
    "attack_ratio": 0.202,
    "health_ratio": 0.798
  },
  {
    "id": "SHRIMP_121125_9417",
    "name": "沉重虾歌",
    "cost": 8,
    "attack": 147,
    "health": 27,
    "wish": "神秘",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 199.97,
    "formula_key": "神秘_勇敢_独特",
    "special_ability": "神秘护盾",
    "description": "勇敢的虾虾，追寻着神秘的梦想，展现出独特的魅力。 战斗力不俗，战斗值约为200点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.654,
      "range_min": 142,
      "range_max": 178,
      "bias_rating": "基本符合",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.83,
      "bias_difference": 0.13
    },
    "attack_ratio": 0.83,
    "health_ratio": 0.17
  },
  {
    "id": "SHRIMP_121125_4573",
    "name": "厚重虾歌",
    "cost": 8,
    "attack": 73,
    "health": 127,
    "wish": "霸气",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "酷炫",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 196.46,
    "formula_key": "霸气_沉稳_酷炫",
    "special_ability": "霸气领域",
    "description": "这只虾虾以沉稳著称，心中燃烧着霸气的火焰，喜欢酷炫的风格。 战斗力不俗，战斗值约为196点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.037,
      "range_min": 178,
      "range_max": 218,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.344,
      "bias_difference": 0.056
    },
    "attack_ratio": 0.344,
    "health_ratio": 0.656
  },
  {
    "id": "SHRIMP_121125_5191",
    "name": "狂野虾光",
    "cost": 8,
    "attack": 124,
    "health": 64,
    "wish": "战斗",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "梦幻",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 183.05,
    "formula_key": "战斗_狡猾_梦幻",
    "special_ability": "战斗狂热",
    "description": "一只战斗的虾虾，性格狡猾，审美梦幻，在战场上诡计多端。 战斗力不俗，战斗值约为183点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.126,
      "range_min": 178,
      "range_max": 218,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.615,
      "bias_difference": 0.015
    },
    "attack_ratio": 0.615,
    "health_ratio": 0.385
  },
  {
    "id": "SHRIMP_121125_9416",
    "name": "暗淡虾仔",
    "cost": 9,
    "attack": 135,
    "health": 85,
    "wish": "霸气",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "梦幻",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 260.47,
    "formula_key": "霸气_狡猾_梦幻",
    "special_ability": "霸气领域",
    "description": "一只狡猾的虾虾，怀有霸气的愿望，审美偏向梦幻。 拥有惊人的战斗力，战斗值约为260点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.549,
      "range_min": 218,
      "range_max": 264,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.636,
      "bias_difference": 0.036
    },
    "attack_ratio": 0.636,
    "health_ratio": 0.364
  },
  {
    "id": "SHRIMP_121125_2391",
    "name": "温柔虾仔",
    "cost": 9,
    "attack": 133,
    "health": 82,
    "wish": "霸气",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "酷炫",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 257.61,
    "formula_key": "霸气_狡猾_酷炫",
    "special_ability": "霸气领域",
    "description": "一只霸气的虾虾，性格狡猾，审美酷炫，在战场上诡计多端。 拥有惊人的战斗力，战斗值约为258点。",
    "balance_analysis": {
      "rating": "偏强",
      "suggestion": "减少攻击或生命值",
      "position_in_range": 0.861,
      "range_min": 218,
      "range_max": 264,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.597,
      "bias_difference": 0.003
    },
    "attack_ratio": 0.597,
    "health_ratio": 0.403
  },
  {
    "id": "SHRIMP_121125_4287",
    "name": "勇敢虾后",
    "cost": 9,
    "attack": 132,
    "health": 64,
    "wish": "战斗",
    "personality": "狡猾",
    "personality_icon": "🦊",
    "personality_color": "#FFD166",
    "aesthetic": "华丽",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 255.53,
    "formula_key": "战斗_狡猾_华丽",
    "special_ability": "战斗狂热",
    "description": "这只虾虾以狡猾著称，心中燃烧着战斗的火焰，喜欢华丽的风格。 拥有惊人的战斗力，战斗值约为256点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.07,
      "range_min": 218,
      "range_max": 264,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.6,
      "actual_attack_ratio": 0.604,
      "bias_difference": 0.004
    },
    "attack_ratio": 0.604,
    "health_ratio": 0.396
  },
  {
    "id": "SHRIMP_121125_5052",
    "name": "明亮虾法",
    "cost": 9,
    "attack": 149,
    "health": 58,
    "wish": "霸气",
    "personality": "勇敢",
    "personality_icon": "🛡️",
    "personality_color": "#FF6B6B",
    "aesthetic": "独特",
    "rarity": "稀有",
    "rarity_color": "#4ECDC4",
    "combat_value": 232.52,
    "formula_key": "霸气_勇敢_独特",
    "special_ability": "霸气领域",
    "description": "拥有勇敢性格的虾虾，致力于霸气的事业，崇尚独特的美学。 拥有惊人的战斗力，战斗值约为233点。",
    "balance_analysis": {
      "rating": "平衡",
      "suggestion": "无需调整",
      "position_in_range": 0.407,
      "range_min": 218,
      "range_max": 264,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.7,
      "actual_attack_ratio": 0.678,
      "bias_difference": 0.022
    },
    "attack_ratio": 0.678,
    "health_ratio": 0.322
  },
  {
    "id": "SHRIMP_121125_9256",
    "name": "冷静虾弓",
    "cost": 9,
    "attack": 95,
    "health": 107,
    "wish": "霸气",
    "personality": "沉稳",
    "personality_icon": "🧘",
    "personality_color": "#A0AEC0",
    "aesthetic": "华丽",
    "rarity": "普通",
    "rarity_color": "#A0AEC0",
    "combat_value": 228.0,
    "formula_key": "霸气_沉稳_华丽",
    "special_ability": "霸气领域",
    "description": "沉稳的虾虾，追寻着霸气的梦想，展现出华丽的魅力。 拥有惊人的战斗力，战斗值约为228点。",
    "balance_analysis": {
      "rating": "偏弱",
      "suggestion": "增加攻击或生命值",
      "position_in_range": 0.217,
      "range_min": 218,
      "range_max": 264,
      "bias_rating": "符合性格偏好",
      "expected_attack_bias": 0.4,
      "actual_attack_ratio": 0.469,
      "bias_difference": 0.069
    },
    "attack_ratio": 0.469,
    "health_ratio": 0.531
  }
];

// 统计信息
function getAdvancedCardStats() {
    const stats = {
        total: advancedShrimpCards.length,
        byPersonality: {},
        byWish: {},
        byAesthetic: {},
        byRarity: {},
        byCost: {},
        avgCost: 0,
        avgAttack: 0,
        avgHealth: 0,
        avgCombatValue: 0
    };
    
    let totalCost = 0;
    let totalAttack = 0;
    let totalHealth = 0;
    let totalCombatValue = 0;
    
    advancedShrimpCards.forEach(card => {
        // 统计性格
        stats.byPersonality[card.personality] = (stats.byPersonality[card.personality] || 0) + 1;
        
        // 统计愿望
        stats.byWish[card.wish] = (stats.byWish[card.wish] || 0) + 1;
        
        // 统计审美
        stats.byAesthetic[card.aesthetic] = (stats.byAesthetic[card.aesthetic] || 0) + 1;
        
        // 统计稀有度
        stats.byRarity[card.rarity] = (stats.byRarity[card.rarity] || 0) + 1;
        
        // 统计费用
        stats.byCost[card.cost] = (stats.byCost[card.cost] || 0) + 1;
        
        // 累计数值
        totalCost += card.cost;
        totalAttack += card.attack;
        totalHealth += card.health;
        totalCombatValue += card.combat_value;
    });
    
    // 计算平均值
    stats.avgCost = (totalCost / advancedShrimpCards.length).toFixed(2);
    stats.avgAttack = (totalAttack / advancedShrimpCards.length).toFixed(2);
    stats.avgHealth = (totalHealth / advancedShrimpCards.length).toFixed(2);
    stats.avgCombatValue = (totalCombatValue / advancedShrimpCards.length).toFixed(2);
    
    return stats;
}

// 根据公式筛选卡牌
function getCardsByFormula(formulaKey) {
    return advancedShrimpCards.filter(card => card.formula_key === formulaKey);
}

// 根据性格筛选卡牌（用于卡组构建）
function getCardsByPersonality(personality) {
    return advancedShrimpCards.filter(card => card.personality === personality);
}

// 根据战斗力范围筛选卡牌
function getCardsByCombatRange(min, max) {
    return advancedShrimpCards.filter(card => card.combat_value >= min && card.combat_value <= max);
}

// 获取卡牌平衡分析摘要
function getBalanceSummary() {
    const summary = { balanced: 0, strong: 0, weak: 0 };
    
    advancedShrimpCards.forEach(card => {
        const rating = card.balance_analysis.rating;
        if (rating === '平衡') summary.balanced++;
        else if (rating === '偏强') summary.strong++;
        else if (rating === '偏弱') summary.weak++;
    });
    
    return summary;
}
