const balancedShrimpCards30HP = [
{
    "id": "SHRIMP_001_4998",
    "name": "自由沉稳自然虾",
    "cost": 5,
    "attack": 9,
    "health": 16,
    "wish": "自由",
    "personality": "沉稳",
    "aesthetic": "自然",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 21.8,
    "base_power": 21.8
  },
{
    "id": "SHRIMP_002_9731",
    "name": "魅力狡猾科技虾",
    "cost": 5,
    "attack": 13,
    "health": 10,
    "wish": "魅力",
    "personality": "狡猾",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "无",
    "total_power": 21.0,
    "base_power": 21.0
  },
{
    "id": "SHRIMP_003_1737",
    "name": "自由勇敢科技虾",
    "cost": 5,
    "attack": 14,
    "health": 9,
    "wish": "自由",
    "personality": "勇敢",
    "aesthetic": "科技",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 21.2,
    "base_power": 21.2
  },
{
    "id": "SHRIMP_004_2104",
    "name": "魅力狡猾科技虾",
    "cost": 9,
    "attack": 13,
    "health": 10,
    "wish": "魅力",
    "personality": "狡猾",
    "aesthetic": "科技",
    "rarity": "普通",
    "effect": "剧毒",
    "total_power": 41.0,
    "base_power": 21.0
  },
{
    "id": "SHRIMP_005_2489",
    "name": "战斗狂野奇幻虾",
    "cost": 9,
    "attack": 16,
    "health": 8,
    "wish": "战斗",
    "personality": "狂野",
    "aesthetic": "奇幻",
    "rarity": "超级稀有",
    "effect": "剧毒",
    "total_power": 42.4,
    "base_power": 22.4
  },
{
    "id": "SHRIMP_006_6795",
    "name": "战斗沉稳科技虾",
    "cost": 7,
    "attack": 11,
    "health": 13,
    "wish": "战斗",
    "personality": "沉稳",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "复生",
    "total_power": 34.6,
    "base_power": 21.4
  },
{
    "id": "SHRIMP_007_3402",
    "name": "自由狂野自然虾",
    "cost": 5,
    "attack": 16,
    "health": 6,
    "wish": "自由",
    "personality": "狂野",
    "aesthetic": "自然",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 20.8,
    "base_power": 20.8
  },
{
    "id": "SHRIMP_008_9851",
    "name": "智慧狂野科技虾",
    "cost": 10,
    "attack": 20,
    "health": 5,
    "wish": "智慧",
    "personality": "狂野",
    "aesthetic": "科技",
    "rarity": "普通",
    "effect": "连击",
    "total_power": 64.0,
    "base_power": 24.0
  },
{
    "id": "SHRIMP_009_2894",
    "name": "战斗勇敢华丽虾",
    "cost": 10,
    "attack": 14,
    "health": 10,
    "wish": "战斗",
    "personality": "勇敢",
    "aesthetic": "华丽",
    "rarity": "超级稀有",
    "effect": "连击",
    "total_power": 50.0,
    "base_power": 22.0
  },
{
    "id": "SHRIMP_010_5006",
    "name": "魅力狡猾自然虾",
    "cost": 7,
    "attack": 13,
    "health": 8,
    "wish": "魅力",
    "personality": "狡猾",
    "aesthetic": "自然",
    "rarity": "超级稀有",
    "effect": "冻结",
    "total_power": 34.4,
    "base_power": 19.4
  },
{
    "id": "SHRIMP_011_2927",
    "name": "自由智慧华丽虾",
    "cost": 5,
    "attack": 11,
    "health": 14,
    "wish": "自由",
    "personality": "智慧",
    "aesthetic": "华丽",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 22.2,
    "base_power": 22.2
  },
{
    "id": "SHRIMP_012_6420",
    "name": "魅力沉稳简约虾",
    "cost": 4,
    "attack": 4,
    "health": 11,
    "wish": "魅力",
    "personality": "沉稳",
    "aesthetic": "简约",
    "rarity": "超级稀有",
    "effect": "复生",
    "total_power": 17.6,
    "base_power": 12.8
  },
{
    "id": "SHRIMP_013_6097",
    "name": "战斗狡猾自然虾",
    "cost": 9,
    "attack": 13,
    "health": 11,
    "wish": "战斗",
    "personality": "狡猾",
    "aesthetic": "自然",
    "rarity": "传说",
    "effect": "剧毒",
    "total_power": 41.8,
    "base_power": 21.8
  },
{
    "id": "SHRIMP_014_5293",
    "name": "霸气沉稳奇幻虾",
    "cost": 5,
    "attack": 10,
    "health": 16,
    "wish": "霸气",
    "personality": "沉稳",
    "aesthetic": "奇幻",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 22.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_015_3694",
    "name": "智慧沉稳科技虾",
    "cost": 6,
    "attack": 9,
    "health": 13,
    "wish": "智慧",
    "personality": "沉稳",
    "aesthetic": "科技",
    "rarity": "超级稀有",
    "effect": "圣盾",
    "total_power": 28.4,
    "base_power": 19.4
  },
{
    "id": "SHRIMP_016_7812",
    "name": "魅力智慧简约虾",
    "cost": 6,
    "attack": 9,
    "health": 14,
    "wish": "魅力",
    "personality": "智慧",
    "aesthetic": "简约",
    "rarity": "超级稀有",
    "effect": "圣盾",
    "total_power": 29.2,
    "base_power": 20.2
  },
{
    "id": "SHRIMP_017_3135",
    "name": "霸气沉稳简约虾",
    "cost": 5,
    "attack": 11,
    "health": 13,
    "wish": "霸气",
    "personality": "沉稳",
    "aesthetic": "简约",
    "rarity": "普通",
    "effect": "无",
    "total_power": 21.4,
    "base_power": 21.4
  },
{
    "id": "SHRIMP_018_7672",
    "name": "自由狂野自然虾",
    "cost": 10,
    "attack": 23,
    "health": 3,
    "wish": "自由",
    "personality": "狂野",
    "aesthetic": "自然",
    "rarity": "普通",
    "effect": "连击",
    "total_power": 71.4,
    "base_power": 25.4
  },
{
    "id": "SHRIMP_019_6109",
    "name": "魅力勇敢奇幻虾",
    "cost": 5,
    "attack": 18,
    "health": 8,
    "wish": "魅力",
    "personality": "勇敢",
    "aesthetic": "奇幻",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 24.4,
    "base_power": 24.4
  },
{
    "id": "SHRIMP_020_1419",
    "name": "战斗勇敢华丽虾",
    "cost": 10,
    "attack": 14,
    "health": 11,
    "wish": "战斗",
    "personality": "勇敢",
    "aesthetic": "华丽",
    "rarity": "超级稀有",
    "effect": "连击",
    "total_power": 50.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_021_1624",
    "name": "魅力智慧科技虾",
    "cost": 6,
    "attack": 7,
    "health": 16,
    "wish": "魅力",
    "personality": "智慧",
    "aesthetic": "科技",
    "rarity": "稀有",
    "effect": "圣盾",
    "total_power": 26.8,
    "base_power": 19.8
  },
{
    "id": "SHRIMP_022_3289",
    "name": "魅力智慧简约虾",
    "cost": 4,
    "attack": 7,
    "health": 14,
    "wish": "魅力",
    "personality": "智慧",
    "aesthetic": "简约",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 18.2,
    "base_power": 18.2
  },
{
    "id": "SHRIMP_023_8956",
    "name": "智慧沉稳华丽虾",
    "cost": 3,
    "attack": 4,
    "health": 11,
    "wish": "智慧",
    "personality": "沉稳",
    "aesthetic": "华丽",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 12.8,
    "base_power": 12.8
  },
{
    "id": "SHRIMP_024_4768",
    "name": "自由智慧自然虾",
    "cost": 6,
    "attack": 11,
    "health": 14,
    "wish": "自由",
    "personality": "智慧",
    "aesthetic": "自然",
    "rarity": "超级稀有",
    "effect": "嘲讽",
    "total_power": 29.2,
    "base_power": 22.2
  },
{
    "id": "SHRIMP_025_7980",
    "name": "霸气沉稳科技虾",
    "cost": 4,
    "attack": 6,
    "health": 14,
    "wish": "霸气",
    "personality": "沉稳",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "无",
    "total_power": 17.2,
    "base_power": 17.2
  },
{
    "id": "SHRIMP_026_2557",
    "name": "霸气勇敢华丽虾",
    "cost": 6,
    "attack": 18,
    "health": 9,
    "wish": "霸气",
    "personality": "勇敢",
    "aesthetic": "华丽",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 25.2,
    "base_power": 25.2
  },
{
    "id": "SHRIMP_027_5405",
    "name": "魅力沉稳自然虾",
    "cost": 5,
    "attack": 10,
    "health": 16,
    "wish": "魅力",
    "personality": "沉稳",
    "aesthetic": "自然",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 22.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_028_6664",
    "name": "智慧狡猾华丽虾",
    "cost": 8,
    "attack": 13,
    "health": 11,
    "wish": "智慧",
    "personality": "狡猾",
    "aesthetic": "华丽",
    "rarity": "传说",
    "effect": "冻结",
    "total_power": 36.8,
    "base_power": 21.8
  },
{
    "id": "SHRIMP_029_6866",
    "name": "战斗勇敢自然虾",
    "cost": 9,
    "attack": 14,
    "health": 11,
    "wish": "战斗",
    "personality": "勇敢",
    "aesthetic": "自然",
    "rarity": "传说",
    "effect": "冲锋",
    "total_power": 43.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_030_4727",
    "name": "自由狡猾奇幻虾",
    "cost": 5,
    "attack": 13,
    "health": 9,
    "wish": "自由",
    "personality": "狡猾",
    "aesthetic": "奇幻",
    "rarity": "普通",
    "effect": "无",
    "total_power": 20.2,
    "base_power": 20.2
  },
{
    "id": "SHRIMP_031_6762",
    "name": "智慧沉稳科技虾",
    "cost": 4,
    "attack": 4,
    "health": 11,
    "wish": "智慧",
    "personality": "沉稳",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "嘲讽",
    "total_power": 18.3,
    "base_power": 12.8
  },
{
    "id": "SHRIMP_032_4055",
    "name": "智慧勇敢华丽虾",
    "cost": 10,
    "attack": 19,
    "health": 6,
    "wish": "智慧",
    "personality": "勇敢",
    "aesthetic": "华丽",
    "rarity": "传说",
    "effect": "冲锋",
    "total_power": 52.3,
    "base_power": 23.8
  },
{
    "id": "SHRIMP_033_1607",
    "name": "智慧智慧奇幻虾",
    "cost": 3,
    "attack": 5,
    "health": 12,
    "wish": "智慧",
    "personality": "智慧",
    "aesthetic": "奇幻",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 14.6,
    "base_power": 14.6
  },
{
    "id": "SHRIMP_034_6340",
    "name": "魅力沉稳简约虾",
    "cost": 4,
    "attack": 6,
    "health": 16,
    "wish": "魅力",
    "personality": "沉稳",
    "aesthetic": "简约",
    "rarity": "普通",
    "effect": "无",
    "total_power": 18.8,
    "base_power": 18.8
  },
{
    "id": "SHRIMP_035_7119",
    "name": "霸气沉稳奇幻虾",
    "cost": 4,
    "attack": 9,
    "health": 13,
    "wish": "霸气",
    "personality": "沉稳",
    "aesthetic": "奇幻",
    "rarity": "传说",
    "effect": "无",
    "total_power": 19.4,
    "base_power": 19.4
  },
{
    "id": "SHRIMP_036_8611",
    "name": "战斗沉稳科技虾",
    "cost": 9,
    "attack": 11,
    "health": 13,
    "wish": "战斗",
    "personality": "沉稳",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "剧毒",
    "total_power": 41.4,
    "base_power": 21.4
  },
{
    "id": "SHRIMP_037_4643",
    "name": "战斗狡猾科技虾",
    "cost": 5,
    "attack": 13,
    "health": 11,
    "wish": "战斗",
    "personality": "狡猾",
    "aesthetic": "科技",
    "rarity": "超级稀有",
    "effect": "无",
    "total_power": 21.8,
    "base_power": 21.8
  },
{
    "id": "SHRIMP_038_6488",
    "name": "智慧勇敢科技虾",
    "cost": 10,
    "attack": 18,
    "health": 6,
    "wish": "智慧",
    "personality": "勇敢",
    "aesthetic": "科技",
    "rarity": "超级稀有",
    "effect": "冲锋",
    "total_power": 49.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_039_7523",
    "name": "自由勇敢科技虾",
    "cost": 4,
    "attack": 13,
    "health": 4,
    "wish": "自由",
    "personality": "勇敢",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "无",
    "total_power": 16.2,
    "base_power": 16.2
  },
{
    "id": "SHRIMP_040_8403",
    "name": "魅力狂野自然虾",
    "cost": 10,
    "attack": 23,
    "health": 4,
    "wish": "魅力",
    "personality": "狂野",
    "aesthetic": "自然",
    "rarity": "普通",
    "effect": "连击",
    "total_power": 72.2,
    "base_power": 26.2
  },
{
    "id": "SHRIMP_041_9391",
    "name": "魅力智慧简约虾",
    "cost": 7,
    "attack": 11,
    "health": 14,
    "wish": "魅力",
    "personality": "智慧",
    "aesthetic": "简约",
    "rarity": "传说",
    "effect": "抽牌",
    "total_power": 33.2,
    "base_power": 22.2
  },
{
    "id": "SHRIMP_042_5606",
    "name": "魅力智慧华丽虾",
    "cost": 5,
    "attack": 9,
    "health": 14,
    "wish": "魅力",
    "personality": "智慧",
    "aesthetic": "华丽",
    "rarity": "传说",
    "effect": "无",
    "total_power": 20.2,
    "base_power": 20.2
  },
{
    "id": "SHRIMP_043_1610",
    "name": "自由狡猾自然虾",
    "cost": 5,
    "attack": 14,
    "health": 8,
    "wish": "自由",
    "personality": "狡猾",
    "aesthetic": "自然",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 20.4,
    "base_power": 20.4
  },
{
    "id": "SHRIMP_044_1288",
    "name": "智慧智慧华丽虾",
    "cost": 6,
    "attack": 11,
    "health": 14,
    "wish": "智慧",
    "personality": "智慧",
    "aesthetic": "华丽",
    "rarity": "传说",
    "effect": "嘲讽",
    "total_power": 29.2,
    "base_power": 22.2
  },
{
    "id": "SHRIMP_045_8903",
    "name": "魅力沉稳奇幻虾",
    "cost": 7,
    "attack": 10,
    "health": 16,
    "wish": "魅力",
    "personality": "沉稳",
    "aesthetic": "奇幻",
    "rarity": "传说",
    "effect": "嘲讽",
    "total_power": 30.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_046_1988",
    "name": "魅力勇敢科技虾",
    "cost": 5,
    "attack": 19,
    "health": 6,
    "wish": "魅力",
    "personality": "勇敢",
    "aesthetic": "科技",
    "rarity": "稀有",
    "effect": "无",
    "total_power": 23.8,
    "base_power": 23.8
  },
{
    "id": "SHRIMP_047_4373",
    "name": "战斗勇敢科技虾",
    "cost": 5,
    "attack": 14,
    "health": 11,
    "wish": "战斗",
    "personality": "勇敢",
    "aesthetic": "科技",
    "rarity": "传说",
    "effect": "无",
    "total_power": 22.8,
    "base_power": 22.8
  },
{
    "id": "SHRIMP_048_1333",
    "name": "霸气智慧华丽虾",
    "cost": 6,
    "attack": 8,
    "health": 14,
    "wish": "霸气",
    "personality": "智慧",
    "aesthetic": "华丽",
    "rarity": "传说",
    "effect": "圣盾",
    "total_power": 27.2,
    "base_power": 19.2
  },
{
    "id": "SHRIMP_049_8110",
    "name": "魅力狂野科技虾",
    "cost": 9,
    "attack": 20,
    "health": 6,
    "wish": "魅力",
    "personality": "狂野",
    "aesthetic": "科技",
    "rarity": "超级稀有",
    "effect": "剧毒",
    "total_power": 44.8,
    "base_power": 24.8
  },
{
    "id": "SHRIMP_050_7792",
    "name": "自由沉稳自然虾",
    "cost": 6,
    "attack": 6,
    "health": 15,
    "wish": "自由",
    "personality": "沉稳",
    "aesthetic": "自然",
    "rarity": "传说",
    "effect": "嘲讽",
    "total_power": 25.5,
    "base_power": 18.0
  }
];

// 🎴 战斗力修正版 (2026-03-16)
// 🔥 系统暴君宣言：效果战斗力计算已修正！
// ✅ 只使用策略页面定义的9种效果！
// ⚖️ 相同战斗力必须对应相同费用！
// 📊 修正了11个无效效果：超杀、亡语、免疫、光环、风怒
// 🦐 总卡牌数: 50张 | 效果: 剧毒、抽牌、调度、冻结、圣盾、冲锋、潜行、连击、嘲讽、复生
